version: "3"
services:
    app:
        container_name: "urban_service"
        restart: always
        build: .
        ports:
            - 3030:3000
        links:
            - docker-mongodb-server
            - mongo-seed
            - docker-redis-server
    docker-mongodb-server:
        container_name: urban_mongo
        image: mongo:4.4.1
        ports:
            - 27018:27017
    mongo-seed:
        image: mongo:4.4.1
        user: 1000:1001
        links:
            - docker-mongodb-server
        volumes:
            - ./:/usr/src/app
        command: mongoimport --host docker-mongodb-server --db urban --collection coordinates --type json --file /usr/src/app/mongo-seed/coordinates.json
    docker-redis-server:
        container_name: urban_redis
        image: redis
        ports:
            - 6380:6379
